#!/bin/bash
if ! docker info > /dev/null 2>&1; then
  echo '("docker error", "Docker daemon is not running", "")' >&2
  exit 1
fi

exec docker run --rm -i -v "$(pwd):/app" -w /app __IMAGE_NAME__ pip "$@"